### ISSUE TITLE
No such file or directory: '<blabla>/aggregate.json'

### ISSUE THREAD

**Issue by Pascal76** [xbb/parsedmarc-docker#1]
Hello,

Thank you for your docker file.
When I run parsedmarc I have an error:

docker run -v /usr/share/GeoIP:/usr/share/GeoIP -v /apache_sites/jbm:/apache_sites/jbm --rm parse_dmarc parsedmarc -c /etc/parsedmarc.ini

   DEBUG:__init__.py:1099:Processing message 464 of 465: UID 1839852
    INFO:__init__.py:805:Parsing mail from postmaster@bbox.fr
   DEBUG:__init__.py:1099:Processing message 465 of 465: UID 1839853
    INFO:__init__.py:805:Parsing mail from postmaster@bbox.fr
Traceback (most recent call last):
  File "/opt/pypy/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "/opt/pypy/lib/pypy3.9/site-packages/parsedmarc/cli.py", line 975, in _main
    process_reports(results)
  File "/opt/pypy/lib/pypy3.9/site-packages/parsedmarc/cli.py", line 81, in process_reports
    save_output(results, output_directory=opts.output,
  File "/opt/pypy/lib/pypy3.9/site-packages/parsedmarc/__init__.py", line 1325, in save_output
    append_json(os.path.join(output_directory, aggregate_json_filename),
  File "/opt/pypy/lib/pypy3.9/site-packages/parsedmarc/__init__.py", line 1265, in append_json
    with open(filename, "r+", newline="\n", encoding="utf-8") as output:
FileNotFoundError: [Errno 2] No such file or directory: '/apache_sites/jbm/dmarc/files/input/aggregate.json'

It is strange because /apache_sites/jbm/dmarc/files/input/ is accessible and writable inside the container.
I don't have this issue outside the container.

The conf file I added (ADD ["etc/parsedmarc.ini", "/etc"])

<blabla>
[mailbox]
watch = False
delete = False
test = True
archive_folder = INBOX/processed

and second issue:  messages are deleted

**Comment by xbb** [comment]
Hi,

are you trying to output the reports to file? Sorry, I haven't tried that, in my case I was using Elasticsearch.

Maybe you should report the issue to the project repo: https://github.com/domainaware/parsedmarc/issues/

In your log I see `with open(filename, "r+", newline="\n", encoding="utf-8") as output:` this could be a bug, it expects that file to exist. Similar issue I guess: https://github.com/domainaware/parsedmarc/issues/355

You can also try with an older version of the image

> The conf file I added (ADD ["etc/parsedmarc.ini", "/etc"])

Are you adding the config file to the image build instead of mapping it via volumes?

**Comment by Pascal76** [comment]
>Are you adding the config file to the image build instead of mapping it via volumes?

Yes. I will try the mapping

+ I will check https://github.com/domainaware/parsedmarc/issues/355 thank you

**Comment by Pascal76** [comment]
by the way
What is the difference between your docker file and the one from parsedmarc ?

**Comment by xbb** [comment]
There wasn't an "official" Dockerfile when I started using it.

It's actually very similar now, only the way the package is installed is different, maybe the image is slightly smaller too.

Before I was using the pypy image as base, now I changed to python:3.9-slim.

I have recently setup automated builds here, you can find the images here (https://github.com/xbb/parsedmarc-docker/pkgs/container/parsedmarc) or Docker Hub for both amd64 and arm64.

Did you solve your original issue?

**Comment by Pascal76** [comment]
no, there is no news on the messages from the forum :(

**Comment by xbb** [comment]
Did you try with version 8.3.0?

**Comment by Pascal76** [comment]
no I prefer waiting a new build (I don't want to fix a bug with a build containing others bugs or obsolete content)

**Comment by Pascal76** [comment]
well, I can't wait anymore
Could you tell me how to find the "ARG REF" for the 8.3.0 code (or other release) please ?

**Comment by xbb** [comment]
See this: https://github.com/xbb/parsedmarc-docker/blob/8.3.0/Dockerfile

For versions before 8.3.2, you can find built images here: https://hub.docker.com/repository/docker/xbblabs/parsedmarc

**Comment by Pascal76** [comment]
it was fixed

**Comment by xbb** [comment]
Nice! Thanks for letting me know
